export const AUDIT_CATEGORIES = [
  "AUTH",
  "CASE",
  "EVIDENCE",
  "CUSTODY",
  "VERIFICATION",
  "LEDGER",
  "REPORT",
  "CASE_PACKET",
  "ANCHOR",
  "SHIELD",
  "ADMIN",
  "ROLE",
  "PERMISSION",
  "TAMPER_TEST",
  "DEMO",
  "WALLET",
  "SYSTEM",
  "BACKUP",
] as const;

export type AuditCategory = (typeof AUDIT_CATEGORIES)[number];

export const AUDIT_SEVERITIES = [
  "INFO",
  "NOTICE",
  "WARNING",
  "HIGH",
  "CRITICAL",
] as const;

export type AuditSeverity = (typeof AUDIT_SEVERITIES)[number];

export const AUDIT_OUTCOMES = ["SUCCESS", "FAILURE", "DENIED", "ERROR"] as const;

export type AuditOutcome = (typeof AUDIT_OUTCOMES)[number];

export const AUDIT_ACTIONS = {
  USER_REGISTERED: "USER_REGISTERED",
  USER_LOGGED_IN: "USER_LOGGED_IN",
  USER_LOGIN_FAILED: "USER_LOGIN_FAILED",
  USER_LOGGED_OUT: "USER_LOGGED_OUT",
  CASE_CREATED: "CASE_CREATED",
  CASE_VIEWED: "CASE_VIEWED",
  EVIDENCE_UPLOADED: "EVIDENCE_UPLOADED",
  EVIDENCE_VIEWED: "EVIDENCE_VIEWED",
  EVIDENCE_INVENTORY_SEARCHED: "EVIDENCE_INVENTORY_SEARCHED",
  CUSTODY_EVENT_ADDED: "CUSTODY_EVENT_ADDED",
  CUSTODY_SIGNATURE_CREATED: "CUSTODY_SIGNATURE_CREATED",
  CUSTODY_SIGNATURE_VERIFIED: "CUSTODY_SIGNATURE_VERIFIED",
  CUSTODY_SIGNATURE_MISSING: "CUSTODY_SIGNATURE_MISSING",
  CUSTODY_SIGNATURE_FAILED: "CUSTODY_SIGNATURE_FAILED",
  EVIDENCE_VERIFICATION_RUN: "EVIDENCE_VERIFICATION_RUN",
  EVIDENCE_VERIFICATION_MATCHED: "EVIDENCE_VERIFICATION_MATCHED",
  EVIDENCE_VERIFICATION_FAILED: "EVIDENCE_VERIFICATION_FAILED",
  EVIDENCE_REPORT_VIEWED: "EVIDENCE_REPORT_VIEWED",
  EVIDENCE_REPORT_EXPORTED: "EVIDENCE_REPORT_EXPORTED",
  CASE_PACKET_VIEWED: "CASE_PACKET_VIEWED",
  CASE_PACKET_EXPORTED: "CASE_PACKET_EXPORTED",
  ANCHOR_VIEWED: "ANCHOR_VIEWED",
  ANCHOR_EXPORTED_JSON: "ANCHOR_EXPORTED_JSON",
  ANCHOR_EXPORTED_TEXT: "ANCHOR_EXPORTED_TEXT",
  ANCHOR_SNAPSHOT_SAVED: "ANCHOR_SNAPSHOT_SAVED",
  ANCHOR_PUBLICATION_UPDATED: "ANCHOR_PUBLICATION_UPDATED",
  ANCHOR_DUPLICATE_PREVENTED: "ANCHOR_DUPLICATE_PREVENTED",
  ANCHOR_COMPARISON_MATCH: "ANCHOR_COMPARISON_MATCH",
  ANCHOR_COMPARISON_MISMATCH: "ANCHOR_COMPARISON_MISMATCH",
  SHIELD_VIEWED: "SHIELD_VIEWED",
  SHIELD_ALERT_ACKNOWLEDGED: "SHIELD_ALERT_ACKNOWLEDGED",
  SHIELD_ACKNOWLEDGEMENT_CLEARED: "SHIELD_ACKNOWLEDGEMENT_CLEARED",
  ADMIN_USERS_VIEWED: "ADMIN_USERS_VIEWED",
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
  USER_ROLE_CHANGE_DENIED: "USER_ROLE_CHANGE_DENIED",
  LAST_ADMIN_DEMOTION_BLOCKED: "LAST_ADMIN_DEMOTION_BLOCKED",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  FORBIDDEN_PAGE_VIEWED: "FORBIDDEN_PAGE_VIEWED",
  TAMPER_TEST_VIEWED: "TAMPER_TEST_VIEWED",
  TAMPER_TEST_BLOCK_TAMPERED: "TAMPER_TEST_BLOCK_TAMPERED",
  TAMPER_TEST_RESTORED: "TAMPER_TEST_RESTORED",
  DEMO_VIEWED: "DEMO_VIEWED",
  DEMO_CASE_CREATED: "DEMO_CASE_CREATED",
  DEMO_ACTION_RUN: "DEMO_ACTION_RUN",
  AUDIT_LOG_VIEWED: "AUDIT_LOG_VIEWED",
  AUDIT_LOG_EXPORTED: "AUDIT_LOG_EXPORTED",
  AUDIT_CHAIN_VALIDATED: "AUDIT_CHAIN_VALIDATED",
  AUDIT_CHAIN_INVALID: "AUDIT_CHAIN_INVALID",
  WALLET_VIEWED: "WALLET_VIEWED",
  TEST_VAULT_SPENT: "TEST_VAULT_SPENT",
  BACKUP_PAGE_VIEWED: "BACKUP_PAGE_VIEWED",
  BACKUP_CREATED: "BACKUP_CREATED",
  BACKUP_DOWNLOADED: "BACKUP_DOWNLOADED",
  BACKUP_VERIFIED: "BACKUP_VERIFIED",
  BACKUP_VERIFICATION_FAILED: "BACKUP_VERIFICATION_FAILED",
  RESTORE_PREVIEWED: "RESTORE_PREVIEWED",
  RESTORE_EXECUTED: "RESTORE_EXECUTED",
  RESTORE_BLOCKED: "RESTORE_BLOCKED",
  PRE_RESTORE_SAFETY_BACKUP_CREATED: "PRE_RESTORE_SAFETY_BACKUP_CREATED",
  DEV_DIAGNOSTIC_VIEWED: "DEV_DIAGNOSTIC_VIEWED",
  DEV_DIAGNOSTIC_RUN: "DEV_DIAGNOSTIC_RUN",
  DEV_DIAGNOSTIC_CHECK_PASSED: "DEV_DIAGNOSTIC_CHECK_PASSED",
  DEV_DIAGNOSTIC_CHECK_FAILED: "DEV_DIAGNOSTIC_CHECK_FAILED",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export type AuditActor = {
  actorId?: string | null;
  actorName?: string | null;
  actorEmail?: string | null;
  actorRole?: string | null;
};

export type RecordAuditEventInput = AuditActor & {
  action: AuditAction | string;
  category: AuditCategory | string;
  severity: AuditSeverity | string;
  outcome: AuditOutcome | string;
  targetType?: string | null;
  targetId?: string | null;
  targetLabel?: string | null;
  route?: string | null;
  method?: string | null;
  permission?: string | null;
  ipAddress?: string | null;
  userAgent?: string | null;
  summary: string;
  metadata?: Record<string, unknown> | null;
  timestamp?: Date;
};

export const GENESIS_AUDIT_HASH = "GENESIS";
